[project]
name = "small-projects-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris", email = "christian.naibaf@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pypdf>=6.16.2",
    "pymupdf>=1.24.0",
    "pytest>=9.1.1",
    "streamlit>=1.45.0",
]

package = false

[tool.pytest.ini_options]
pythonpath = ["src"]
